// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProiectMoldovanAlexWebAppMVC.Data;

#nullable disable

namespace ProiectMoldovanAlexWebAppMVC.Migrations
{
    [DbContext(typeof(ProiectMoldovanAlexWebAppMVCContext))]
    [Migration("20251207143908_feb")]
    partial class feb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Brand", b =>
                {
                    b.Property<int>("BrandID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandID");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Car", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BrandID")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EngineID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Seats")
                        .HasColumnType("int");

                    b.Property<int>("YearFabrication")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BrandID");

                    b.HasIndex("EngineID");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Engine", b =>
                {
                    b.Property<int>("EngineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EngineID"));

                    b.Property<int>("Cylinders")
                        .HasColumnType("int");

                    b.Property<double>("Displacement")
                        .HasColumnType("float");

                    b.Property<int>("HorsePower")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EngineID");

                    b.ToTable("Engine");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int?>("CarID")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OwnerID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("CarID");

                    b.HasIndex("OwnerID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Owner", b =>
                {
                    b.Property<int>("OwnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrivingConduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfAccidents")
                        .HasColumnType("int");

                    b.HasKey("OwnerID");

                    b.ToTable("Owner");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Car", b =>
                {
                    b.HasOne("ProiectMoldovanAlexWebAppMVC.Models.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandID");

                    b.HasOne("ProiectMoldovanAlexWebAppMVC.Models.Engine", "Engine")
                        .WithMany("Cars")
                        .HasForeignKey("EngineID");

                    b.Navigation("Brand");

                    b.Navigation("Engine");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Order", b =>
                {
                    b.HasOne("ProiectMoldovanAlexWebAppMVC.Models.Car", "Car")
                        .WithMany("Orders")
                        .HasForeignKey("CarID");

                    b.HasOne("ProiectMoldovanAlexWebAppMVC.Models.Owner", "Owner")
                        .WithMany("Orders")
                        .HasForeignKey("OwnerID");

                    b.Navigation("Car");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Car", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Engine", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("ProiectMoldovanAlexWebAppMVC.Models.Owner", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
